### ISSUE TITLE
Bug in build dataset code

### ISSUE THREAD

**Issue by chang-github-00** [szxiangjn/world-model-for-language-model#3] opened 2023-08-07 10:36 UTC
Hi,

I tried to replicate the dataset [here](https://github.com/szxiangjn/world-model-for-language-model/blob/main/data/train/train_plan_gen.json) by running https://github.com/szxiangjn/world-model-for-language-model/blob/main/build_dataset/mcts/mcts.py.  

Dependency: VirtualHome (https://github.com/szxiangjn/world-model-for-language-model/tree/main/build_dataset/mcts/virtualhome), use_cores=1

1. There are missing import files in lines 13-15:
  `from evolving_graph.scripts import read_script_from_list_string`
  `from evolving_graph.execution import ScriptExecutor, Relation`
  `from evolving_graph.environment import *`
  
  After changing it to virtualhome.simulation.evolving_graph, the objects could be imported:
  `from virtualhome.simulation.evolving_graph.scripts import read_script_from_list_string`
  `from virtualhome.simulation.evolving_graph.execution import ScriptExecutor, Relation`
  `from virtualhome.simulation.evolving_graph.environment import *`
  
2. After changing the import to virtualhome.simulation.evolving_graph, the code raise error `virtualhome.simulation.evolving_graph.execution.ExecutionException: Execution of Action.WALK is not supported` at 
  ```reward, new_vh_state, unachieved_goals, success, modified_action = self.env.transition(action, self.vh_state, self.goals, self.unachieved_goals)```

**Comment by szxiangjn** [comment] 2023-08-29 16:56
Hi,

Sorry for the late reply. I just saw the issue. I will look into it later this week.

**Comment by szxiangjn** [comment] 2023-08-30 16:23
Hi,

I cannot reproduce the error on my side. Could you share the whole error message?

My suspicion is that you installed the official `virtualhome` package from https://github.com/xavierpuigf/virtualhome. This won't work with our code since we modified some code of `virtualhome`. Please uninstall it and try again.

**Comment by szxiangjn** [comment] 2023-09-05 17:46
Closing the issue for now. Feel free to reopen it if the issue is not resolved.

**Closed as completed by szxiangjn** 2023-09-05 17:46 UTC
